services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Tu_Pass123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - datos_sql:/var/opt/mssql
    networks:
      - backend

  serviceproduct:
    build:
      context: ./registroservice
      dockerfile: Dockerfile
    container_name: registroservice
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=bdMetronics;User=sa;Password=Tu_Pass123!;
    ports:
      - "5120:80"
    networks:
      - backend

volumes:
  datos_sql:

networks:
  backend:
