USE [master]
GO

/****** Object:  Database [bdMetronics]    Script Date: 4/06/2025 10:41:34 a. m. ******/
CREATE DATABASE [bdMetronics]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bdMetronics', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\bdMetronics.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'bdMetronics_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\bdMetronics_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bdMetronics].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bdMetronics] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bdMetronics] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bdMetronics] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bdMetronics] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bdMetronics] SET ARITHABORT OFF 
GO

ALTER DATABASE [bdMetronics] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bdMetronics] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bdMetronics] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bdMetronics] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bdMetronics] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bdMetronics] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bdMetronics] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bdMetronics] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bdMetronics] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bdMetronics] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bdMetronics] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bdMetronics] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bdMetronics] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bdMetronics] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bdMetronics] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bdMetronics] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bdMetronics] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bdMetronics] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [bdMetronics] SET  MULTI_USER 
GO

ALTER DATABASE [bdMetronics] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bdMetronics] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bdMetronics] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bdMetronics] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [bdMetronics] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bdMetronics] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [bdMetronics] SET QUERY_STORE = OFF
GO

ALTER DATABASE [bdMetronics] SET  READ_WRITE 
GO


